### ISSUE TITLE
File Picker Issues

### ISSUE THREAD

**Issue by SpotComms** [Streetwalrus/android_usb_msd#2]
Loading images from the file picker doesn't work as they are all greyed out no matter internal or external. Using the CM File Manager shortcut works but then is limited to internal storage and doesn't allow navigation to external storage.

Android: LineageOS 14.1 (7.1.1)
Version: 0.3.1.1 (F-Droid)

**Comment by ronnystandtke** [comment]
I also couldn't select anything with the build-in file picker but using the CM file manager for selecting the ISO on my SD card worked, probably because I gave it root rights.
But even after selecting and mounting my ISO file, it didn't show up on my Linux box. It only offered MTP mounts...
Is there anything (tests, tracefiles, debug logs, ...) I can provide to help fixing this issue?

**Comment by Streetwalrus** [comment]
I'm using the file picker provided by Android. I usually go through the CM file manager myself. There isn't much I can do besides using a file picker library but I'm not really keen on the idea.

Open to suggestions anyhow.

**Comment by Streetwalrus** [comment]
As far as the file picker itself is concerned, I still can't repro. Lineage has pulled its file manager now, but I've been able to use Amaze successfully (available on F-Droid).

I've had issues with actual mounting myself but it looks like a rebuild fixed the issue so I bumped the version number, please report back.

**Comment by Streetwalrus** [comment]
A friend pointed this issue out to me today so I took another look. b89be04dc9ca48113ea371d12a8a5a6ce1900416 should fix it. Resolving the path for some files will require proper support for runtime permissions but right now it's way past midnight and I don't feel like doing this at all. Will release once it's done.
